### ISSUE TITLE
Config Screen not loading in Adapt Authoring Tool

### ISSUE THREAD

**Issue by nfon-christophe** [walkgrovedev/adapt-walkgrove-dialogue#1]
Hi. I'm trying to use your dialogue component in the authoring tool, but when I click to edit the settings the screen remains blank. Other components in your repos work fine in the authoring tool. Can you advise?

**Comment by walkgrovedev** [comment]
Hi nfon-christophe,

I'm sorry, I developed these components to use within the framework and don't use the authoring tool.
As the framework is open source, I thought it was good to share the components I create, for anyone who wished to use them :O)

Looking at the component template file (hbs) the only difference I can see, is that i haven't got a class on the speech bubbles to set them a 'widgets'. I've added this and saved to this repo:

![image](https://user-images.githubusercontent.com/69632389/122592971-e73c7600-d05c-11eb-833f-9b10d86156e4.png)

Please let me know if you still have problems and I'll try to help.

Kind regards,

Laura

**Comment by nfon-christophe** [comment]
Hi Laura,
That's fantastic. Thank you very much for coming back to me so quickly though. Very much appreciated.
I have given it a go and find out (I think) what the issue was. There was some code needed in the button schema.
I have submitted a pull request.
Have a great weekend!
Regards
Christophe
